# Prepaid Electricity Tracker Package v2
# Works with Power Meter for HA v1.0 (ESP32-C6 CT clamp)
# City Power Johannesburg tiered tariffs
# Block 1: 0-600 kWh @ R3.9094/kWh | Block 2: >600 kWh @ R4.6475/kWh

sensor:
  - platform: integration
    source: sensor.sonoff_1000e104f7_power
    name: sonoff_grid_energy_total
    unique_id: sonoff_grid_energy_total
    unit_prefix: k
    unit_time: h
    method: left

utility_meter:
  sonoff_grid_energy_daily:
    source: sensor.sonoff_grid_energy_total
    name: Sonoff Grid Energy Daily
    cycle: daily
  sonoff_grid_energy_monthly:
    source: sensor.sonoff_grid_energy_total
    name: Sonoff Grid Energy Monthly
    cycle: monthly

input_number:
  prepaid_electricity_balance:
    name: Prepaid Electricity Balance
    min: 0
    max: 50000
    step: 0.01
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:lightning-bolt
  prepaid_electricity_topup_amount:
    name: Top-up Amount
    min: 0
    max: 5000
    step: 0.1
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:plus-circle
  prepaid_electricity_cumulative_usage:
    name: Cumulative Grid Usage
    min: 0
    max: 1000000
    step: 0.001
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:counter
  prepaid_electricity_topup_reference:
    name: Usage Reference at Top-up
    min: 0
    max: 1000000
    step: 0.001
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:bookmark
  prepaid_electricity_low_threshold:
    name: Low Balance Alert Threshold
    min: 0
    max: 500
    step: 1
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:alert
  prepaid_electricity_monthly_usage:
    name: Monthly Grid Usage
    min: 0
    max: 10000
    step: 0.001
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:calendar-month
  prepaid_electricity_yesterday_usage:
    name: Yesterday Usage
    min: 0
    max: 1000
    step: 0.001
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:history
  prepaid_electricity_7day_usage:
    name: Last 7 Days Usage
    min: 0
    max: 10000
    step: 0.001
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:calendar-week
  prepaid_tariff_block1:
    name: Tariff Block 1 (0-600 kWh)
    min: 0
    max: 10
    step: 0.0001
    unit_of_measurement: "R/kWh"
    mode: box
    icon: mdi:currency-zar
    initial: 3.9094
  prepaid_tariff_block2:
    name: Tariff Block 2 (>600 kWh)
    min: 0
    max: 10
    step: 0.0001
    unit_of_measurement: "R/kWh"
    mode: box
    icon: mdi:currency-zar
    initial: 4.6475
  prepaid_electricity_sync_value:
    name: Actual Meter Balance
    min: 0
    max: 50000
    step: 0.1
    unit_of_measurement: "kWh"
    mode: box
    icon: mdi:sync

input_select:
  prepaid_electricity_source:
    name: Grid Import Source Sensor
    options:
      - sensor.grid_energy_daily
      - sensor.sonoff_grid_energy_daily
      - sensor.deyeinvertercombined_summary_day_grid_import_buy
      - sensor.deyeinvertermaster_summary_day_grid_import_buy
      - sensor.deyeinverterslave_summary_day_grid_import_buy
    initial: sensor.grid_energy_daily
    icon: mdi:flash

input_datetime:
  prepaid_electricity_last_topup:
    name: Last Top-up Time
    has_date: true
    has_time: true
    icon: mdi:clock

input_button:
  prepaid_electricity_topup_button:
    name: Add Units to Balance
    icon: mdi:plus-circle-outline
  prepaid_electricity_sync_button:
    name: Sync Balance to Meter
    icon: mdi:sync

template:
  - sensor:
      - name: "Prepaid Electricity Current Balance"
        unique_id: prepaid_electricity_current_balance
        unit_of_measurement: "kWh"
        state_class: measurement
        icon: mdi:lightning-bolt-circle
        state: >-
          {% set balance = states('input_number.prepaid_electricity_balance') | float(0) %}
          {% set cumulative = states('input_number.prepaid_electricity_cumulative_usage') | float(0) %}
          {% set reference = states('input_number.prepaid_electricity_topup_reference') | float(0) %}
          {% set source = states(states('input_select.prepaid_electricity_source')) | float(0) %}
          {% set usage_since_topup = (cumulative - reference) + source %}
          {% set current = balance - usage_since_topup %}
          {{ [current, 0] | max | round(2) }}
      - name: "Prepaid Electricity Usage Since Topup"
        unique_id: prepaid_electricity_usage_since_topup
        unit_of_measurement: "kWh"
        state_class: total_increasing
        icon: mdi:transmission-tower-import
        state: >-
          {% set cumulative = states('input_number.prepaid_electricity_cumulative_usage') | float(0) %}
          {% set reference = states('input_number.prepaid_electricity_topup_reference') | float(0) %}
          {% set source = states(states('input_select.prepaid_electricity_source')) | float(0) %}
          {% set usage = (cumulative - reference) + source %}
          {{ [usage, 0] | max | round(3) }}
      - name: "Prepaid Electricity Today Usage"
        unique_id: prepaid_electricity_today_usage
        unit_of_measurement: "kWh"
        state_class: total_increasing
        icon: mdi:calendar-today
        state: >-
          {{ states(states('input_select.prepaid_electricity_source')) | float(0) | round(3) }}
      - name: "Prepaid Electricity Average Daily Usage"
        unique_id: prepaid_electricity_avg_daily
        unit_of_measurement: "kWh"
        icon: mdi:chart-line
        state: >-
          {% set seven_day = states('input_number.prepaid_electricity_7day_usage') | float(0) %}
          {% if seven_day > 0 %}
            {{ (seven_day / 7) | round(2) }}
          {% else %}
            {% set yesterday = states('input_number.prepaid_electricity_yesterday_usage') | float(0) %}
            {{ yesterday | round(2) if yesterday > 0 else 'unknown' }}
          {% endif %}
      - name: "Prepaid Electricity Days Remaining"
        unique_id: prepaid_electricity_days_remaining
        unit_of_measurement: "days"
        icon: mdi:calendar-clock
        state: >-
          {% set balance = states('sensor.prepaid_electricity_current_balance') | float(0) %}
          {% set avg_daily = states('sensor.prepaid_electricity_average_daily_usage') %}
          {% if avg_daily not in ['unknown', 'unavailable', '0', '0.0'] and avg_daily | float(0) > 0 %}
            {{ (balance / (avg_daily | float)) | round(1) }}
          {% else %}
            unknown
          {% endif %}
      - name: "Prepaid Electricity Empty Date"
        unique_id: prepaid_electricity_empty_date
        icon: mdi:calendar-alert
        state: >-
          {% set days = states('sensor.prepaid_electricity_days_remaining') %}
          {% if days not in ['unknown', 'unavailable'] and days | float(0) > 0 %}
            {{ (now() + timedelta(days=days | float)) | as_timestamp | timestamp_custom('%a %d %b %Y') }}
          {% else %}
            unknown
          {% endif %}
      - name: "Prepaid Electricity Monthly Usage"
        unique_id: prepaid_electricity_monthly_usage_sensor
        unit_of_measurement: "kWh"
        state_class: total_increasing
        icon: mdi:calendar-month
        state: >-
          {% set monthly = states('input_number.prepaid_electricity_monthly_usage') | float(0) %}
          {% set today = states(states('input_select.prepaid_electricity_source')) | float(0) %}
          {{ (monthly + today) | round(2) }}
      - name: "Prepaid Electricity Current Tariff Block"
        unique_id: prepaid_electricity_tariff_block
        icon: mdi:tag
        state: >-
          {% set monthly = states('sensor.prepaid_electricity_monthly_usage') | float(0) %}
          {{ 'Block 1' if monthly <= 600 else 'Block 2' }}
      - name: "Prepaid Electricity Current Rate"
        unique_id: prepaid_electricity_current_rate
        unit_of_measurement: "R/kWh"
        icon: mdi:currency-zar
        state: >-
          {% set monthly = states('sensor.prepaid_electricity_monthly_usage') | float(0) %}
          {% set block1 = states('input_number.prepaid_tariff_block1') | float(3.9094) %}
          {% set block2 = states('input_number.prepaid_tariff_block2') | float(4.6475) %}
          {{ block1 if monthly <= 600 else block2 }}
      - name: "Prepaid Electricity Balance Value"
        unique_id: prepaid_electricity_balance_value
        unit_of_measurement: "R"
        icon: mdi:cash
        state: >-
          {% set balance = states('sensor.prepaid_electricity_current_balance') | float(0) %}
          {% set monthly = states('sensor.prepaid_electricity_monthly_usage') | float(0) %}
          {% set block1_rate = states('input_number.prepaid_tariff_block1') | float(3.9094) %}
          {% set block2_rate = states('input_number.prepaid_tariff_block2') | float(4.6475) %}
          {% set block1_remaining = [600 - monthly, 0] | max %}
          {% if balance <= block1_remaining %}
            {{ (balance * block1_rate) | round(2) }}
          {% else %}
            {{ (block1_remaining * block1_rate + (balance - block1_remaining) * block2_rate) | round(2) }}
          {% endif %}
      - name: "Prepaid Electricity Monthly Cost"
        unique_id: prepaid_electricity_monthly_cost
        unit_of_measurement: "R"
        icon: mdi:cash-multiple
        state: >-
          {% set monthly = states('sensor.prepaid_electricity_monthly_usage') | float(0) %}
          {% set block1_rate = states('input_number.prepaid_tariff_block1') | float(3.9094) %}
          {% set block2_rate = states('input_number.prepaid_tariff_block2') | float(4.6475) %}
          {% if monthly <= 600 %}
            {{ (monthly * block1_rate) | round(2) }}
          {% else %}
            {{ (600 * block1_rate + (monthly - 600) * block2_rate) | round(2) }}
          {% endif %}
      - name: "Prepaid Electricity Low Balance"
        unique_id: prepaid_electricity_low_balance
        icon: mdi:alert-circle
        state: >-
          {% set balance = states('sensor.prepaid_electricity_current_balance') | float(0) %}
          {% set threshold = states('input_number.prepaid_electricity_low_threshold') | float(50) %}
          {{ balance < threshold }}
      - name: "Prepaid Electricity Active Source"
        unique_id: prepaid_electricity_active_source
        icon: mdi:information
        state: >-
          {% set source = states('input_select.prepaid_electricity_source') %}
          {% if 'grid_energy_daily' in source and 'sonoff' not in source %}
            ESP32 CT Clamp
          {% elif 'sonoff' in source %}
            Sonoff Meter
          {% elif 'combined' in source %}
            Deye Combined
          {% elif 'master' in source %}
            Deye Master
          {% elif 'slave' in source %}
            Deye Slave
          {% else %}
            {{ source }}
          {% endif %}

automation:
  - alias: "Prepaid Electricity: Process Top-up"
    id: prepaid_electricity_process_topup
    trigger:
      - platform: state
        entity_id: input_button.prepaid_electricity_topup_button
    condition:
      - condition: template
        value_template: "{{ states('input_number.prepaid_electricity_topup_amount') | float(0) > 0 }}"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_balance
        data:
          value: >-
            {% set current = states('sensor.prepaid_electricity_current_balance') | float(0) %}
            {% set topup = states('input_number.prepaid_electricity_topup_amount') | float(0) %}
            {{ current + topup }}
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_topup_reference
        data:
          value: >-
            {% set cumulative = states('input_number.prepaid_electricity_cumulative_usage') | float(0) %}
            {% set today = states(states('input_select.prepaid_electricity_source')) | float(0) %}
            {{ cumulative + today }}
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.prepaid_electricity_last_topup
        data:
          datetime: "{{ now().isoformat() }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_topup_amount
        data:
          value: 0
      - service: persistent_notification.create
        data:
          title: "Electricity Top-up Processed"
          message: "New balance: {{ states('sensor.prepaid_electricity_current_balance') }} kWh"
          notification_id: "prepaid_topup_confirm"

  - alias: "Prepaid Electricity: Sync Balance"
    id: prepaid_electricity_sync_balance
    trigger:
      - platform: state
        entity_id: input_button.prepaid_electricity_sync_button
    condition:
      - condition: template
        value_template: "{{ states('input_number.prepaid_electricity_sync_value') | float(0) > 0 }}"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_balance
        data:
          value: "{{ states('input_number.prepaid_electricity_sync_value') | float(0) }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_topup_reference
        data:
          value: >-
            {% set cumulative = states('input_number.prepaid_electricity_cumulative_usage') | float(0) %}
            {% set today = states(states('input_select.prepaid_electricity_source')) | float(0) %}
            {{ cumulative + today }}
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_sync_value
        data:
          value: 0
      - service: persistent_notification.create
        data:
          title: "Balance Synchronized"
          message: "Tracker is now in sync with your meter."
          notification_id: "prepaid_sync_confirm"

  - alias: "Prepaid Electricity: Daily Rollover"
    id: prepaid_electricity_daily_rollover
    trigger:
      - platform: time
        at: "23:59:55"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_yesterday_usage
        data:
          value: "{{ states(states('input_select.prepaid_electricity_source')) | float(0) }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_cumulative_usage
        data:
          value: >-
            {% set c = states('input_number.prepaid_electricity_cumulative_usage') | float(0) %}
            {% set t = states(states('input_select.prepaid_electricity_source')) | float(0) %}
            {{ c + t }}
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_monthly_usage
        data:
          value: >-
            {% set m = states('input_number.prepaid_electricity_monthly_usage') | float(0) %}
            {% set t = states(states('input_select.prepaid_electricity_source')) | float(0) %}
            {{ m + t }}
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_7day_usage
        data:
          value: >-
            {% set d7 = states('input_number.prepaid_electricity_7day_usage') | float(0) %}
            {% set t = states(states('input_select.prepaid_electricity_source')) | float(0) %}
            {{ [d7 + t - (d7 / 7), 0] | max }}
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_balance
        data:
          value: "{{ states('sensor.prepaid_electricity_current_balance') | float(0) }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_topup_reference
        data:
          value: "{{ states('input_number.prepaid_electricity_cumulative_usage') | float(0) }}"

  - alias: "Prepaid Electricity: Monthly Reset"
    id: prepaid_electricity_monthly_reset
    trigger:
      - platform: time
        at: "00:00:05"
    condition:
      - condition: template
        value_template: "{{ now().day == 1 }}"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_monthly_usage
        data:
          value: 0

  - alias: "Prepaid Electricity: Low Balance Alert"
    id: prepaid_electricity_low_balance_alert
    trigger:
      - platform: template
        value_template: >-
          {% set balance = states('sensor.prepaid_electricity_current_balance') | float(999) %}
          {% set threshold = states('input_number.prepaid_electricity_low_threshold') | float(50) %}
          {{ balance < threshold and balance > 0 }}
    condition:
      - condition: template
        value_template: >-
          {% set last = state_attr('automation.prepaid_electricity_low_balance_alert', 'last_triggered') %}
          {{ last is none or (now() - last).total_seconds() > 86400 }}
    action:
      - service: notify.whatsapp
        data:
          message: >-
            ⚡ LOW ELECTRICITY BALANCE ⚡
            Balance: {{ states('sensor.prepaid_electricity_current_balance') }} kWh
            Value: R{{ states('sensor.prepaid_electricity_balance_value') }}
            Est. days left: {{ states('sensor.prepaid_electricity_days_remaining') }}
            Please top-up soon!
      - service: persistent_notification.create
        data:
          title: "⚡ Low Electricity Balance"
          message: >-
            Balance: {{ states('sensor.prepaid_electricity_current_balance') }} kWh
            (R{{ states('sensor.prepaid_electricity_balance_value') }}).
            Estimated {{ states('sensor.prepaid_electricity_days_remaining') }} days remaining.
          notification_id: "prepaid_low_balance"

  - alias: "Prepaid Electricity: Clear Low Balance Alert"
    id: prepaid_electricity_clear_low_alert
    trigger:
      - platform: template
        value_template: >-
          {% set balance = states('sensor.prepaid_electricity_current_balance') | float(0) %}
          {% set threshold = states('input_number.prepaid_electricity_low_threshold') | float(50) %}
          {{ balance >= threshold }}
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: "prepaid_low_balance"

  - alias: "Prepaid Electricity: Initialize on Startup"
    id: prepaid_electricity_startup_init
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: template
        value_template: "{{ states('input_number.prepaid_electricity_low_threshold') | float(0) == 0 }}"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.prepaid_electricity_low_threshold
        data:
          value: 50
